[project]
name = "pistomp-midi-bridge"
version = "0.1.0"
description = "A python MIDI bridge between a pistomp and a MIDI controller."
readme = "README.md"
license = "MIT"
authors = [
    { name = "Eduardo Vicente", email = "eduardomcvicente@gmail.com" }
]
requires-python = "==3.11.2"
dependencies = [
    "mido==1.2.10",
    "websockets==10.4",
    "python-rtmidi>=1.5.8",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.3",
]

[project.scripts]
pistomp-midi-bridge = "pistomp_midi_bridge.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13"]
build-backend = "uv_build"

[tool.pytest.ini_options]
pythonpath = ["."]

